=== ZombiesRus5/soase_plugin/SosePlugin/src/entity_definitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/element_definitions/" targetNamespace="http://www.example.org/element_definitions/">
    <element name="entity_definitions" type="tns:entityDefinitions"></element>

    <complexType name="entityDefinitions">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="structure" type="tns:structure" minOccurs="0"/>
    		<element name="condition_field" type="tns:conditionalField" minOccurs="0"/>
    		<element name="element_rule" type="tns:elementRule" minOccurs="0"/>
    	</sequence>
    </complexType>

    <complexType name="structure">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="helpText" type="string" minOccurs="0"/>
    		<element name="structure" type="tns:structure" minOccurs="0"/>
    		<element name="iterative_field" type="tns:iterativeField" minOccurs="0"/>
    		<element name="field" type="tns:elementRule" minOccurs="0"/>
    		<element name="condition_field" type="tns:conditionalField" minOccurs="0"/>
    		<element name="structure_reference" type="tns:structureReference" minOccurs="0"/>
    		<element name="condition_reference" type="tns:conditionReference" minOccurs="0"/>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="required" type="boolean"></attribute>
    	<attribute name="ordered" type="boolean"></attribute>
    	<attribute name="help" type="string"></attribute>
    	<attribute name="version" type="tns:versionType"></attribute>
    </complexType>

    <complexType name="iterativeField">
    	<sequence minOccurs="1" maxOccurs="2">
    		<element name="helpText" type="string" minOccurs="0"/>
    		<element name="structure" type="tns:structure" minOccurs="0"/>
    		<element name="iterative_field" type="tns:iterativeField" minOccurs="0"/>
    		<element name="field" type="tns:elementRule" minOccurs="0"/>
    		<element name="condition_field" type="tns:conditionalField" minOccurs="0"/>
    		<element name="structure_reference" type="tns:structureReference" minOccurs="0"/>
    		<element name="condition_reference" type="tns:conditionReference" minOccurs="0"/>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="required" type="boolean"></attribute>
    	<attribute name="limit" type="integer"></attribute>
    	<attribute name="help" type="string"></attribute>
    	<attribute name="version" type="tns:versionType"></attribute>
    </complexType>

	<complexType name="structureReference">
		<attribute name="name" type="string"></attribute>
    	<attribute name="required" type="boolean"></attribute>
		<attribute name="type" type="string"></attribute>
    	<attribute name="help" type="string"></attribute>
    	<attribute name="version" type="tns:versionType"></attribute>
	</complexType>
	
	<complexType name="conditionReference">
		<attribute name="name" type="string"></attribute>
    	<attribute name="required" type="boolean"></attribute>
		<attribute name="type" type="string"></attribute>
    	<attribute name="help" type="string"></attribute>
	</complexType>
	
	<complexType name="conditionalField">
		<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="helpText" type="string" minOccurs="0"/>
			<element name="condition" type="tns:conditionType"></element>
		</sequence>
		<attribute name="name" type="string"></attribute>
     	<attribute name="required" type="boolean"></attribute>
    	<attribute name="help" type="string"></attribute>
    	<attribute name="version" type="tns:versionType"></attribute>
	</complexType>
	
	<complexType name="conditionType">
    	<sequence minOccurs="1" maxOccurs="unbounded">
     		<element name="helpText" type="string" minOccurs="0"/>
    		<element name="value" type="tns:ValueType" minOccurs="0"/>
    		<element name="structure" type="tns:structure" minOccurs="0"/>
    		<element name="iterative_field" type="tns:iterativeField" minOccurs="0"/>
    		<element name="field" type="tns:elementRule" minOccurs="0"/>
    		<element name="condition_field" type="tns:conditionalField" minOccurs="0"/>
    		<element name="structure_reference" type="tns:structureReference" minOccurs="0"/>
    		<element name="condition_reference" type="tns:conditionReference" minOccurs="0"/>
		</sequence>
		<attribute name="value" type="string"></attribute>
 	    <attribute name="required" type="boolean"></attribute>
    	<attribute name="version" type="tns:versionType"></attribute>
	</complexType>
	
	<complexType name="ValueType" >
		<simpleContent>
			<extension base="string">
				<attribute name="version" type="string"/>
				<attribute name="help" type="string"/>
			</extension>
		</simpleContent>
	</complexType>
	
	<complexType name="elementRule">
		<sequence>
    		<element name="helpText" type="string" minOccurs="0"/>
			<element name="value" type="tns:ValueType" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="name" type="string"></attribute>
		<attribute name="type" type="string"></attribute>
		<attribute name="required" type="boolean"></attribute>
		<attribute name="validation" type="tns:validationType"></attribute>
		<attribute name="values" type="string"></attribute>
    	<attribute name="help" type="string"></attribute>
    	<attribute name="version" type="tns:versionType"></attribute>
    	<attribute name="constraint" type="string"></attribute>
    	<attribute name="referenceType" type="string"></attribute>
	</complexType>
	
	<simpleType name="versionType">
		<restriction base="string">
			<enumeration value="Vanilla" />
			<enumeration value="Entrenchment" />
			<enumeration value="EntrenchmentOnly" />
			<enumeration value="Diplomacy" />
			<enumeration value="DiplomacyOnly" />
			<enumeration value="Rebellion" />
			<enumeration value="NotRebellion" />
			<enumeration value="NotDiplomacyOrRebellion" />
			<enumeration value="Rebellion185" />
			<enumeration value="Rebellion193" />
			<enumeration value="Rebellion194"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="validationType">
		<restriction base="string">
			<enumeration value="Any"></enumeration>
			<enumeration value="Simple"></enumeration>
			<enumeration value="StringInfo"></enumeration>
			<enumeration value="Brush"></enumeration>
			<enumeration value="Mesh"></enumeration>
			<enumeration value="Explosion"></enumeration>
			<enumeration value="Texture"></enumeration>
			<enumeration value="Sound"></enumeration>
			<enumeration value="Entity"></enumeration>
			<enumeration value="Research"></enumeration>
			<enumeration value="Particle"></enumeration>
			<enumeration value="Integer"></enumeration>
			<enumeration value="Decimal"></enumeration>
			<enumeration value="Structure"></enumeration>
			<enumeration value="Boolean"></enumeration>
			<enumeration value="Color"></enumeration>
			<enumeration value="Position"></enumeration>
			<enumeration value="Orientation"></enumeration>
			<enumeration value="Coordinate"></enumeration>
			<enumeration value="Theme"></enumeration>
			<enumeration value="SoundFile"></enumeration>
			<enumeration value="GalaxyDesign"></enumeration>
			<enumeration value="GalaxyTemplate"></enumeration>
			<enumeration value="GalaxyOrbitBodyType"></enumeration>
			<enumeration value="TemplateName"></enumeration>
			<enumeration value="MeshPoint"></enumeration>
		</restriction>
	</simpleType>

</schema>

=== ZombiesRus5/soase_plugin/SosePlugin/src/galaxy_scenario_def.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:entity_definitions xmlns:tns="http://www.example.org/element_definitions/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/element_definitions/ entity_definitions.xsd ">
	<structure name="GalaxyScenarioDef">
		<iterative_field name="starTypeCount">
			<structure_reference required="false" name="starType" type="OrbitBodyDesign"/>
		</iterative_field>
		<iterative_field name="planetTypeCount">
			<structure_reference required="false" name="planetType" type="OrbitBodyDesign"/>
		</iterative_field>
		<iterative_field name="orbitBodyTypeCount">
			<structure_reference required="false" name="orbitBodyType" type="OrbitBodyType"/>
		</iterative_field>
		<iterative_field name="planetItemTypeCount">
			<structure_reference required="false" name="planetItemType" type="EntityDesign"/>
		</iterative_field>
		<iterative_field name="playerTypeCount">
			<structure_reference required="false" name="playerType" type="EntityDesign"/>
		</iterative_field>
		<iterative_field name="planetItemsTemplateCount">
			<structure_reference required="false" name="planetItemsTemplate" type="TemplateType"/>
		</iterative_field>
		<iterative_field name="validPictureGroups">
			<field required="false" name="pictureGroup" validation="Any" />
		</iterative_field>
		<iterative_field name="validThemeGroups">
			<field required="false" name="themeGroup"  validation="Any" />
		</iterative_field>
		<iterative_field name="autoAddPlayers" version="Rebellion185">
			<structure_reference required="false" name="player" type="PlayerStructure" />
		</iterative_field>
		<iterative_field name="npcPlayers" version="Rebellion193">
			<structure_reference required="false" name="player" type="PlayerStructure" />
		</iterative_field>
		<field name="npcMiltiaPlayerCountPerGalaxy" validation="Decimal" version="Rebellion193"/>
		<field name="autoAddMiltiaPlayerCountPerGalaxy" validation="Decimal" version="Rebellion185"/>
		<iterative_field name="autoAddMilitiaPlayers" version="Rebellion185">
			<structure_reference required="false" name="player" type="PlayerStructure" />
		</iterative_field>
	</structure>
		
	<structure name="OrbitBodyDesign">
		<field name="designName" validation="Any"/>
		<field name="designStringId" validation="StringInfo"/>
		<iterative_field name="orbitBodyTypeCount">
			<field required="false" name="orbitBodyType" validation="GalaxyOrbitBodyType"/>
		</iterative_field>
	</structure>
	
	<structure name="OrbitBodyType">
		<field name="typeName" validation="Any" />
		<field name="entityDefName" validation="Entity"/>
		<field name="defaultTemplateName" validation="GalaxyTemplate" />
	</structure>
	
	<structure name="EntityDesign">
		<field name="designName" validation="Any" />
		<field name="entityDefName" validation="Entity" />
	</structure>

	<structure name="TemplateType">
		<field name="templateName" validation="Any" />
		<iterative_field name="subTemplates">
			<field required="false" name="template" validation="GalaxyTemplate" />
		</iterative_field>
		<iterative_field name="groups">
			<structure_reference required="false" name="group" type="GroupType"/>
		</iterative_field>
	</structure>
	
	<structure name="GroupType">
		<structure name="condition">
			<condition_field name="type">
				<condition value="Always">
					<field name="param" validation="Any" />
				</condition>
				<condition value="NoPlanetOwner">
					<field name="param" validation="Any" />
				</condition>
				<condition value="PlanetOwnerIsMilitiaWithChance">
					<field name="param" validation="Decimal" />
				</condition>
				<condition value="NoPlanetOwnerWithChance">
					<field name="param" validation="Decimal" />
				</condition>
				<condition value="PlanetOwnerIsMilitia">
					<field name="param" validation="Any" />
				</condition>
				<condition value="PlanetOwnerIsRaceNormalStart">
					<field name="param" validation="GalaxyDesign" />
				</condition>
				<condition value="PlanetOwnerIsRaceQuickStart">
					<field name="param" validation="GalaxyDesign" />
				</condition>
				<condition value="PlanetOwnerIsMinorFactionWithFactionName">
					<field name="param" validation="GalaxyDesign" />
				</condition>
				<condition value="PlanetHasAnyOwner">
					<field name="param" validation="Any" />
				</condition>				
			</condition_field>
			<!-- <field name="type" validation="Simple" >
				<value></value>
				<value>Always</value>
				<value>NoPlanetOwner</value>
				<value>PlanetOwnerIsMilitiaWithChance</value>
				<value>NoPlanetOwnerWithChance</value>
				<value>PlanetOwnerIsMilitia</value>
				<value>PlanetOwnerIsRaceNormalStart</value>
				<value>PlanetOwnerIsRaceQuickStart</value>
				<value>PlanetOwnerIsMinorFactionWithFactionName</value>
				<value>PlanetHasAnyOwner</value>
			</field>
			<field name="param" validation="Any" /> -->
		</structure>
		<field name="owner" validation="GalaxyDesign"/>
		<field name="colonizeChance" validation="Integer"/>
		<iterative_field name="items">
			<field required="false" name="item" validation="GalaxyDesign" />
		</iterative_field>
	</structure>
	
	<structure name="PlayerStructure">
		<field name="designName" validation="Any" />
		<field name="inGameName" validation="Any" />
		<field name="overrideRaceName" validation="Any" />
		<field name="teamIndex" validation="Integer" />
		<field name="startingCredits" validation="Integer" />
		<field name="startingMetal" validation="Integer" />
		<field name="startingCrystal" validation="Integer" />
		<condition_field name="playerType" version="Rebellion193">
			<condition><value version="Rebellion">NPCMinorFaction</value>
				<field name="minorFactionPlayerDefName" validation="Any" version="Rebellion193"/>
			</condition>
			<condition>
				<value>NPCPirateRaider</value>
				<value>NPCRebel</value>
				<value>NPCOccupationVictory</value>
				<value>NPCMadVasari</value>
				<value>NPCMilitia</value>
				<value help="Normal is used in Galaxy Map Files">Normal</value>
			</condition>
		</condition_field>
		<field name="isNormalPlayer" validation="Boolean" version="Rebellion185"/>
		<field name="isRaidingPlayer" validation="Boolean" version="Rebellion185"/>
		<field name="isInsurgentPlayer" validation="Boolean" version="Rebellion185"/>
		<field name="isOccupationPlayer" validation="Boolean" version="Rebellion185"/> 
		<field name="isMadVasariPlayer" validation="Boolean" version="Rebellion185"/>
		<field name="themeGroup" validation="Any" />
		<field name="themeIndex" validation="Integer" />
		<field name="pictureGroup" validation="Any" />
		<field name="pictureIndex" validation="Integer" />
	</structure>
</tns:entity_definitions>

=== ZombiesRus5/soase_plugin/SosePlugin/src/useCustomHyperspaceEffects.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:entity_definitions xmlns:tns="http://www.example.org/element_definitions/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/element_definitions/ entity_definitions.xsd ">

	<condition_field name="useCustomHyperspaceEffects">
		<condition><value>TRUE</value>
			<structure name="effects">
				<field required="true" name="chargeUpEffectName" validation="Particle" version="Rebellion193"/>
				<field required="true" name="chargeUpEffectNameBetweenStars" validation="Particle" version="Rebellion193"/>
				<field required="true" name="chargeUpEffectNameDestabilized" validation="Particle" version="Rebellion193"/>
				<field required="true" name="chargeUpEffectSoundID" validation="Sound"/>
				<field required="true" name="travelEffectName" validation="Particle" version="Rebellion193"/>
				<field required="true" name="travelEffectNameBetweenStars" validation="Particle" version="Rebellion193"/>
				<field required="true" name="travelEffectNameDestabilized" validation="Particle" version="Rebellion193"/>
				<field required="true" name="travelEffectSoundID" validation="Sound"/>
				<field required="true" name="exitEffectName" validation="Particle" version="Rebellion193"/>
				<field required="true" name="exitEffectSoundID" validation="Sound"/>
			</structure>
		</condition>
		<condition><value>FALSE</value></condition>
	</condition_field>
</tns:entity_definitions>

=== ZombiesRus5/soase_plugin/SosePlugin/bin/galaxy_scenario_def.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:entity_definitions xmlns:tns="http://www.example.org/element_definitions/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/element_definitions/ entity_definitions.xsd ">
	<structure name="GalaxyScenarioDef">
		<iterative_field name="starTypeCount">
			<structure_reference required="false" name="starType" type="OrbitBodyDesign"/>
		</iterative_field>
		<iterative_field name="planetTypeCount">
			<structure_reference required="false" name="planetType" type="OrbitBodyDesign"/>
		</iterative_field>
		<iterative_field name="orbitBodyTypeCount">
			<structure_reference required="false" name="orbitBodyType" type="OrbitBodyType"/>
		</iterative_field>
		<iterative_field name="planetItemTypeCount">
			<structure_reference required="false" name="planetItemType" type="EntityDesign"/>
		</iterative_field>
		<iterative_field name="playerTypeCount">
			<structure_reference required="false" name="playerType" type="EntityDesign"/>
		</iterative_field>
		<iterative_field name="planetItemsTemplateCount">
			<structure_reference required="false" name="planetItemsTemplate" type="TemplateType"/>
		</iterative_field>
		<iterative_field name="validPictureGroups">
			<field required="false" name="pictureGroup" validation="Any" />
		</iterative_field>
		<iterative_field name="validThemeGroups">
			<field required="false" name="themeGroup"  validation="Any" />
		</iterative_field>
		<iterative_field name="autoAddPlayers" version="Rebellion185">
			<structure_reference required="false" name="player" type="PlayerType" />
		</iterative_field>
		<iterative_field name="npcPlayers" version="Rebellion193">
			<structure_reference required="false" name="player" type="PlayerType" />
		</iterative_field>
		<field name="autoAddMiltiaPlayerCountPerGalaxy" validation="Decimal"/>
		<iterative_field name="autoAddMilitiaPlayers">
			<structure_reference required="false" name="player" type="PlayerType" />
		</iterative_field>
	</structure>
		
	<structure name="OrbitBodyDesign">
		<field name="designName" validation="Any"/>
		<field name="designStringId" validation="StringInfo"/>
		<iterative_field name="orbitBodyTypeCount">
			<field required="false" name="orbitBodyType" validation="GalaxyOrbitBodyType"/>
		</iterative_field>
	</structure>
	
	<structure name="OrbitBodyType">
		<field name="typeName" validation="Any" />
		<field name="entityDefName" validation="Entity"/>
		<field name="defaultTemplateName" validation="GalaxyTemplate" />
	</structure>
	
	<structure name="EntityDesign">
		<field name="designName" validation="Any" />
		<field name="entityDefName" validation="Entity" />
	</structure>

	<structure name="TemplateType">
		<field name="templateName" validation="Any" />
		<iterative_field name="subTemplates">
			<field required="false" name="template" validation="GalaxyTemplate" />
		</iterative_field>
		<iterative_field name="groups">
			<structure_reference required="false" name="group" type="GroupType"/>
		</iterative_field>
	</structure>
	
	<structure name="GroupType">
		<structure name="condition">
			<field name="type" validation="Simple" >
				<value></value>
				<value>Always</value>
				<value>NoPlanetOwner</value>
				<value>PlanetOwnerIsMilitiaWithChance</value>
				<value>NoPlanetOwnerWithChance</value>
				<value>PlanetOwnerIsMilitia</value>
				<value>PlanetOwnerIsRaceNormalStart</value>
				<value>PlanetOwnerIsRaceQuickStart</value>
				<value>PlanetOwnerIsMinorFactionWithFactionName</value>
			</field>
			<field name="param" validation="Any" />
		</structure>
		<field name="owner" validation="Any"/>
		<field name="colonizeChance" validation="Integer"/>
		<iterative_field name="items">
			<field required="false" name="item" validation="GalaxyDesign" />
		</iterative_field>
	</structure>
	
	<structure name="PlayerType">
		<field name="designName" validation="Any" />
		<field name="inGameName" validation="Any" />
		<field name="overrideRaceName" validation="Any" />
		<field name="teamIndex" validation="Integer" />
		<field name="startingCredits" validation="Integer" />
		<field name="startingMetal" validation="Integer" />
		<field name="startingCrystal" validation="Integer" />
		<field name="playerType" validation="Any" version="Rebellion193"/>
		<field name="minorFactionPlayerDefName" validation="Any" version="Rebellion193"/>
		<field name="isNormalPlayer" validation="Boolean" version="Rebellion185"/>
		<field name="isRaidingPlayer" validation="Boolean" version="Rebellion185"/>
		<field name="isInsurgentPlayer" validation="Boolean" version="Rebellion185"/>
		<field name="isOccupationPlayer" validation="Boolean" version="Rebellion185"/> 
		<field name="isMadVasariPlayer" validation="Boolean" version="Rebellion185"/>
		<field name="themeGroup" validation="Any" />
		<field name="themeIndex" validation="Integer" />
		<field name="pictureGroup" validation="Any" />
		<field name="pictureIndex" validation="Integer" />
		
	</structure>
</tns:entity_definitions>
